
MODULE_NAME=Safety

MODUL_DIR = $(MODULE_NAME)/

MODULE_SOURCE+= safety_rtos.c \
				safety_runtime.c \
				safety_powersupply.c \
				safety_startup.c \
				STM32_Safety_STL_API/ROMTestStl.c \
				STM32_Safety_STL_API/CPUTestStl.c \
				STM32_Safety_STL_API/RAMTestStl.c \
				STM32_Safety_STL_API/SafetyStl.c \
				build/Safety_DependantFunctions.c \

TEST_C_SOURCE =

TEST_CXX_SOURCE += safety_module_tests.cc

LIBCERT_SOURCE += $(addprefix $(MODULE_NAME)/,$(MODULE_SOURCE))

UNITTEST_C_SRC += $(addprefix LibCert/$(MODULE_NAME)/,$(TEST_C_SOURCE))

UNITTEST_CXX_SRC += $(addprefix LibCert/$(MODULE_NAME)/,$(TEST_CXX_SOURCE))

axivion_analysis.ir : lib${MODULE_NAME}.a
	irlink -s --include_unused lib${MODULE_NAME}.a axivion_analysis.ir

GLOBAL_DEFINES+=-DFEAT_RTOS=1 -DFEAT_DEBUG=0 -DUSE_EMBOS=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_STARTUP=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_RUNTIME=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_STARTUP_RAM=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_STARTUP_ROM=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_STARTUP_CPU=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_RUNTIME_RAM=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_RUNTIME_ROM=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_RUNTIME_CPU=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_RUNTIME_POWERSUPPLY=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_WATCHDOG=1
GLOBAL_DEFINES+=-DFEATURE_MAX116XX_EXTERNAL_ADC=1
GLOBAL_DEFINES+=-DWATCHDOG_WINDOW_PERCENT=10
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_RUNTIME_REGISTER=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_RUNTIME_PROGFLOW=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_USE_STL=1
GLOBAL_DEFINES+=-DFEATURE_SAFETYCHECK_USE_TIMER=0
GLOBAL_DEFINES+=-DEN61508_RAMTEST_FROM_SAFETY_TASK=1
GLOBAL_DEFINES+=-DEN61508_RAMTEST_USE_TIMER=0
GLOBAL_DEFINES+=-DFEATURE_RAMTEST_INCLUDE_TESTREGION2=1
GLOBAL_DEFINES+=-DFEATURE_RAMTEST_INCLUDE_TESTREGION3=1
GLOBAL_DEFINES+=-DFEATURE_ERROR_LOGGING=1
GLOBAL_DEFINES+=-DFEAT_MSG_INTERPRETER=0
GLOBAL_DEFINES+=-DWATCHDOG_DEFAULT_CHANNEL=0
GLOBAL_DEFINES+=-DfpADCIN_VCC
GLOBAL_DEFINES+=-DfpADCIN_VCC1
GLOBAL_DEFINES+=-DfpADCIN_VCC2
GLOBAL_DEFINES+=-DfpADCIN_VCC3
GLOBAL_DEFINES+=-DfpADCIN_VCC4
GLOBAL_DEFINES+=-DfpADCIN_VCC5
GLOBAL_DEFINES+=-DfpADCIN_ICC
GLOBAL_DEFINES+=-DVOLTAGE_VCC_FACTOR=16.902f
GLOBAL_DEFINES+=-DCURRENT_FACTOR=16.902f
GLOBAL_DEFINES+=-DTMP144_UART_CHANNEL=CHANNEL_CREATE(9,2)
GLOBAL_DEFINES+=-DTEMPERATURE_WARNING_MIN=(-35.0f)
GLOBAL_DEFINES+=-DTEMPERATURE_WARNING_MAX=(80.0f)
GLOBAL_DEFINES+=-DTEMPERATURE_ERROR_MIN=(-40.0f)
GLOBAL_DEFINES+=-DTEMPERATURE_ERROR_MAX=(85.0f)
GLOBAL_DEFINES+=-DPOWER_LIMIT_MAX_WATT=(3.5f)
GLOBAL_DEFINES+=-DPOWER_LIMIT_WARNING_MAX_WATT=(3.4f)
GLOBAL_DEFINES+=-DFEATURE_SAFETY_RUNTIME_PROGFLOW_USE_RTC_M41T62
GLOBAL_DEFINES+=-DRTC_CHANNEL=CHANNEL_CREATE(9,1)
GLOBAL_DEFINES+=-DRTC_I2C_ADDRESS=(0xD0)
GLOBAL_DEFINES+=-DOS_TICK_FREQ=(1000u)
GLOBAL_DEFINES+=-DPROCESS_SAFETY_TIME_MS=(4000u)
GLOBAL_DEFINES+=-DMAX116XX_FEAT_4CHANNEL_ADC=(1)
GLOBAL_DEFINES+=-DMAX116XX_FEAT_12CHANNEL_ADC=(1)
GLOBAL_DEFINES+=-DHARD_ERR_INTERN_ADC_STARTUP=(0x01)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL1_TO_CHECK_IS_12CHANNEL=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL1_TO_CHECK_CHANNEL=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL1_TO_CHECK_R1=(10.0f)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL1_TO_CHECK_R2=(20.0f)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL1_TO_CHECK_LIMIT_MIN_VOLT=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL1_TO_CHECK_LIMIT_MAX_VOLT=(10)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL2_TO_CHECK_IS_12CHANNEL=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL2_TO_CHECK_CHANNEL=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL2_TO_CHECK_R1=(10.0f)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL2_TO_CHECK_R2=(20.0f)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL2_TO_CHECK_LIMIT_MIN_VOLT=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL2_TO_CHECK_LIMIT_MAX_VOLT=(10)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL3_TO_CHECK_IS_12CHANNEL=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL3_TO_CHECK_CHANNEL=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL3_TO_CHECK_R1=(10.0f)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL3_TO_CHECK_R2=(20.0f)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL3_TO_CHECK_LIMIT_MIN_VOLT=(1)
GLOBAL_DEFINES+=-DEXT_ADC_CHANNEL3_TO_CHECK_LIMIT_MAX_VOLT=(10)

GLOBAL_DEFINES+=-DFEATURE_MPU_RTOS_AL_MPU_ENABLE=0

GLOBAL_DEFINES += -Ibuild/embOS/Start/Inc -D__ARM_ARCH_7M__

GLOBAL_DEFINES+=-DSTM32G491xx
GLOBAL_DEFINES+=-D__PROGRAM_START

LIB_INCLUDE += -I..
LIB_INCLUDE += -I.
LIB_INCLUDE += -Ibuild
LIB_INCLUDE += -Ibuild/LibCert/ST_Driver/
LIB_INCLUDE += -Ibuild/LibQM/ST_Driver/
LIB_INCLUDE += -Ibuild/LibCert/ST_Driver/CMSIS/Core/Include
LIB_INCLUDE += -Ibuild/LibCert/ST_Driver/CMSIS/Device/ST/STM32G4xx/Include
LIB_INCLUDE += -Ibuild/LibCert/ST_Driver/STM32G4xx_HAL_Driver/Inc

-include build/Driver_Common/Makefile_module
-include build/Driver_Common/Makefile_module.unittest

MAKE_DEPS+=LibCert/$(MODULE_NAME)/Makefile
